select *
from customer 
limit 20;


-- what is the total revenue generated by male vs female customers 
select 
	gender,
	sum(purchase_amount)
from customer 
group by
	gender;

-- which customers used a discount but still spent more than the average purchase amount?
with avg_spent as (
	select 
		round(avg(purchase_amount),2) as average_amount_spent
	from customer
),
discount_applies_customers as (
	select 
		customer_id,
		discount_applied,
		sum(purchase_amount) as total_amount_spent
	from customer 
	where discount_applied = 'Yes'
	group by 
		customer_id,
		discount_applied
)
select 
	customer_id,
	discount_applied,
	total_amount_spent,
	average_amount_spent
from 
	avg_spent
cross join 
	discount_applies_customers
where 
	total_amount_spent>average_amount_spent
;

-- which are the top 5 products with the highest average review ratings?
select 
	item_purchased,
	round(avg(review_rating::numeric),2) as average_product_rating
from customer
group by 
	item_purchased
order by avg(review_rating) desc
limit 5
;

-- compare the average purchase amounts between standard and express shipping
select 
	shipping_type,
	round(avg(purchase_amount),2) as average_purchase_amount
from customer
where shipping_type in ('Express', 'Standard')
group by
	shipping_type
order by round(avg(purchase_amount),2) desc
;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
select *
from customer;